title: Miguel Fuentes
email: mmfuentes@umass.edu
description: >- # this means to ignore newlines until "baseurl:"
  Miguel Fuentes's personal website
baseurl: "" # the subpath of your site, e.g. /blog
domain: "miguel-fuentes.github.io"  
url: "https://miguel-fuentes.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  Miguel-Fuentes
source:      .
destination: ./_site
includes:    ./_includes